# Generated by Django 4.2.23 on 2025-07-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliceIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "police_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="police_a_identity",
                        to="inference.player",
                        verbose_name="警察A",
                    ),
                ),
                (
                    "police_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="police_b_identity",
                        to="inference.player",
                        verbose_name="警察B",
                    ),
                ),
            ],
            options={"verbose_name": "警察身份", "verbose_name_plural": "警察身份",},
        ),
    ]
