# Generated by Django 3.2.2 on 2025-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameplayGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('police', '预言家'), ('villager', '平民'), ('mafia', '狼人')], max_length=10, verbose_name='角色')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '玩法思路',
                'verbose_name_plural': '玩法思路',
                'ordering': ['role', '-created_at'],
            },
        ),
    ]
