# Generated by Django 3.2.2 on 2025-08-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_gameplayguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayguide',
            name='role',
            field=models.CharField(choices=[('police', '预言家'), ('villager', '平民'), ('mafia', '狼人'), ('witch', '女巫'), ('guard', '守卫')], max_length=10, verbose_name='角色'),
        ),
    ]
