# Generated by Django 4.2.23 on 2025-07-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0003_alter_judgment_label_alter_nightcheck_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WerewolfProbabilityAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "probability_increase",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="增加概率(%)"
                    ),
                ),
                ("reason", models.TextField(verbose_name="调整原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inference.player",
                        verbose_name="目标玩家",
                    ),
                ),
            ],
            options={
                "verbose_name": "匪徒概率调整",
                "verbose_name_plural": "匪徒概率调整",
                "ordering": ["-created_at"],
            },
        ),
    ]
