# Generated by Django 4.2.23 on 2025-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0004_werewolfprobabilityadjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OppositionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="组合名称")),
                ("reason", models.TextField(blank=True, verbose_name="对立原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "players",
                    models.ManyToManyField(to="inference.player", verbose_name="对立玩家"),
                ),
            ],
            options={
                "verbose_name": "对立组合",
                "verbose_name_plural": "对立组合",
                "ordering": ["-created_at"],
            },
        ),
    ]
