# Generated by Django 4.2.23 on 2025-07-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0004_werewolfprobabilityadjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OppositionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="对立原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opposition_player1",
                        to="inference.player",
                        verbose_name="对立玩家1",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opposition_player2",
                        to="inference.player",
                        verbose_name="对立玩家2",
                    ),
                ),
            ],
            options={
                "verbose_name": "对立组合",
                "verbose_name_plural": "对立组合",
                "ordering": ["-created_at"],
                "unique_together": {("player1", "player2")},
            },
        ),
    ]
